spring.application.name=main-service

spring.datasource.url=jdbc:postgresql://localhost:5432/lms_main
spring.datasource.username=${DB_USERNAME:lms_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.level.kz.bitlab.springboot.mainservice=DEBUG
