spring.application.name=main-service

spring.datasource.url=jdbc:postgresql://localhost:5432/lms_main
spring.datasource.username=${DB_USERNAME:lms_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.level.kz.bitlab.springboot.mainservice=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/bitlab-lms

keycloak.token-uri=http://localhost:8081/realms/bitlab-lms/protocol/openid-connect/token
keycloak.client-id=main-service
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
